name: project_management_app
description: A comprehensive project management application with task tracking, team collaboration, and reporting features.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State management
  provider: ^6.0.5
  
  # Routing and navigation
  go_router: ^10.1.0
  
  # HTTP client
  http: ^1.1.0
  
  # Storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  
  # Internationalization
  intl: ^0.18.1
  
  # UI components
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  animations: ^2.0.7
  shimmer: ^3.0.0
  fl_chart: ^0.63.0
  table_calendar: ^3.0.9
  flutter_colorpicker: ^1.0.3
  material_color_utilities: ^0.5.0
  dropdown_button2: ^2.3.8
  flutter_markdown: ^0.6.17
  
  # Forms
  form_validator: ^2.1.1
  
  # Date and time
  jiffy: ^6.2.1
  
  # Utils
  uuid: ^4.0.0
  equatable: ^2.0.5
  rxdart: ^0.27.7
  logger: ^2.0.1
  fpdart: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  device_info_plus: ^9.0.3
  
  # Testing
  mockito: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/images/splash_logo.png
  image_dark: assets/images/splash_logo_dark.png
  
  android_12:
    color: "#FFFFFF"
    color_dark: "#121212"
    image: assets/images/splash_logo.png
    image_dark: assets/images/splash_logo_dark.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"